telepathy-glib: relax -Werror=incompatible-pointer-types for GCC 14+
GCC 14 promotes -Wincompatible-pointer-types to an error by default. This
release passes a wrongly-typed GDestroyNotify to g_ptr_array_new_full:

  telepathy-glib/protocol.c:1794:42: error: passing argument 2 of
  'g_ptr_array_new_full' from incompatible pointer type
  [-Wincompatible-pointer-types]

Add -Wno-error=incompatible-pointer-types so the build completes.

Signed-off-by: Khem Raj <raj.khem@gmail.com>