assimp: disable warnings-as-errors to fix GCC 16 build
GCC 16 flags a set-but-unused variable in MS3DLoader.cpp and assimp builds
with -Werror:

  code/AssetLib/MS3D/MS3DLoader.cpp:633:28: error: variable 'qu' set but not
  used [-Werror=unused-but-set-variable=]
  cc1plus: all warnings being treated as errors

Pass -DASSIMP_WARNINGS_AS_ERRORS=OFF so upstream warnings do not break the
build.

Signed-off-by: Khem Raj <raj.khem@gmail.com>