avro-c++: relax -Werror=unused-but-set-variable for GCC 16
GCC 16 reports a set-but-unused variable in the JSON parser, and avro builds
with -Werror:

  lang/c++/impl/json/JsonIO.cc:296:30: error: variable 'n' set but not used
  [-Werror=unused-but-set-variable=]

Extend the existing toolchain-gcc -Wno-error workaround to cover it.

Signed-off-by: Khem Raj <raj.khem@gmail.com>